<?php

return [
    'PAYMONGO_PUBLIC_KEY' => env('PAYMONGO_PUBLIC_KEY'),
    'PAYMONGO_SECRET_KEY' => env('PAYMONGO_SECRET_KEY'),

    'GOOGLE_CLIENT_ID' => env('GOOGLE_CLIENT_ID'),
    'GOOGLE_CLIENT_SECRET' => env('GOOGLE_CLIENT_SECRET'),
    'GOOGLE_REDIRECT_URI' => env('GOOGLE_REDIRECT_URI'),
];
